import { PrismaClient, PromoCodeScope } from '@prisma/client';

export async function seedPromoCodes(prisma: PrismaClient): Promise<void> {
  const promoCodes = [
    {
      code: 'WELCOME10',
      description: 'Welcome discount for new customers',
      discountPercentage: 10,
      maxDiscountAmount: null,
      minOrderValue: 100.0,
      maxUsage: 1000,
      usageCount: 0,
      isActive: true,
      expiresAt: new Date('2025-12-31'),
      scope: PromoCodeScope.ALL,
    },
    {
      code: 'GAMING20',
      description: '20% off gaming configurations',
      discountPercentage: 20,
      maxDiscountAmount: null,
      minOrderValue: 500.0,
      maxUsage: 500,
      usageCount: 0,
      isActive: true,
      expiresAt: new Date('2025-08-31'),
      scope: PromoCodeScope.ALL,
    },
    {
      code: 'SUMMER50',
      description: '5% off with max $50 discount - summer sale',
      discountPercentage: 5,
      maxDiscountAmount: 50.0,
      minOrderValue: 200.0,
      maxUsage: 300,
      usageCount: 0,
      isActive: true,
      expiresAt: new Date('2025-07-31'),
      scope: PromoCodeScope.ALL,
    },
    {
      code: 'COMPONENTS15',
      description: '15% off individual components',
      discountPercentage: 15,
      maxDiscountAmount: null,
      minOrderValue: 75.0,
      maxUsage: 750,
      usageCount: 0,
      isActive: true,
      expiresAt: new Date('2025-10-31'),
      scope: PromoCodeScope.ALL,
    },
    {
      code: 'BLACKFRIDAY',
      description: 'Black Friday mega discount',
      discountPercentage: 25,
      maxDiscountAmount: null,
      minOrderValue: 300.0,
      maxUsage: 2000,
      usageCount: 0,
      isActive: true,
      expiresAt: new Date('2025-11-30'),
      scope: PromoCodeScope.ALL,
    },
    {
      code: 'PERIPHERAL10',
      description: '10% off peripherals',
      discountPercentage: 10,
      maxDiscountAmount: null,
      minOrderValue: 50.0,
      maxUsage: 400,
      usageCount: 0,
      isActive: true,
      expiresAt: new Date('2025-09-30'),
      scope: PromoCodeScope.ALL,
    },
    {
      code: 'STUDENT',
      description: 'Student discount program',
      discountPercentage: 12,
      maxDiscountAmount: null,
      minOrderValue: 100.0,
      maxUsage: 1500,
      usageCount: 0,
      isActive: true,
      expiresAt: new Date('2025-12-31'),
      scope: PromoCodeScope.ALL,
    },
    {
      code: 'FIRSTBUILD',
      description:
        'First time PC builder discount - 10% off with max $75 discount',
      discountPercentage: 10,
      maxDiscountAmount: 75.0,
      minOrderValue: 400.0,
      maxUsage: 200,
      usageCount: 0,
      isActive: true,
      expiresAt: new Date('2025-11-15'),
      scope: PromoCodeScope.ALL,
    },
    {
      code: 'UPGRADE25',
      description: '5% off upgrade components with max $25 discount',
      discountPercentage: 5,
      maxDiscountAmount: 25.0,
      minOrderValue: 150.0,
      maxUsage: 600,
      usageCount: 0,
      isActive: true,
      expiresAt: new Date('2025-08-15'),
      scope: PromoCodeScope.ALL,
    },
    {
      code: 'LOYALTY',
      description: 'Loyalty program exclusive discount',
      discountPercentage: 18,
      maxDiscountAmount: null,
      minOrderValue: 250.0,
      maxUsage: 100,
      usageCount: 0,
      isActive: true,
      expiresAt: new Date('2025-12-31'),
      scope: PromoCodeScope.ALL,
    },
  ];

  await prisma.promoCode.createMany({ data: promoCodes, skipDuplicates: true });
}
